// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from lll_supervisor_msgs:msg/SupervisorMetadata.idl
// generated code does not contain a copyright notice

#ifndef LLL_SUPERVISOR_MSGS__MSG__DETAIL__SUPERVISOR_METADATA__STRUCT_H_
#define LLL_SUPERVISOR_MSGS__MSG__DETAIL__SUPERVISOR_METADATA__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "std_msgs/msg/detail/header__struct.h"
// Member 'input_desired'
// Member 'input_actual'
// Member 'input_failsafe'
#include "rosidl_runtime_c/primitives_sequence.h"
// Member 'generation_extras'
// Member 'filtering_extras'
#include "rosidl_runtime_c/string.h"

/// Struct defined in msg/SupervisorMetadata in the package lll_supervisor_msgs.
typedef struct lll_supervisor_msgs__msg__SupervisorMetadata
{
  std_msgs__msg__Header header;
  /// Timestamp of the state used for filtering
  int64_t t_state;
  /// Timestamp of the input used for filtering
  int64_t t_input;
  rosidl_runtime_c__double__Sequence input_desired;
  rosidl_runtime_c__double__Sequence input_actual;
  rosidl_runtime_c__double__Sequence input_failsafe;
  /// Current closest distance to 3D space obstacles (0->inf)
  double h_distance_current;
  /// Current value of safety function (0->1)
  double h_current;
  /// Predicted value of safety function over failsafe trajectory (0->1)
  double h_predicted;
  /// Normalized distance between desired and filtered input (0->1)
  double input_modification;
  /// Measure of control authority given to the human/autonomy stack (0->1)
  /// 0. if no control authority, 1. if complete control authority
  double regulation_map_size;
  /// Extra data generated by kernel generator
  rosidl_runtime_c__String__Sequence generation_extras;
  /// Extra data generated by input filter
  rosidl_runtime_c__String__Sequence filtering_extras;
} lll_supervisor_msgs__msg__SupervisorMetadata;

// Struct for a sequence of lll_supervisor_msgs__msg__SupervisorMetadata.
typedef struct lll_supervisor_msgs__msg__SupervisorMetadata__Sequence
{
  lll_supervisor_msgs__msg__SupervisorMetadata * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} lll_supervisor_msgs__msg__SupervisorMetadata__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // LLL_SUPERVISOR_MSGS__MSG__DETAIL__SUPERVISOR_METADATA__STRUCT_H_
